### ISSUE TITLE
Node documentation package-lock.json and yarn.lock

### ISSUE THREAD

**Issue by josspo** [maoo/security-scanning#207]
Following the documentation, Node step 2
`rm -rf node_modules package-lock.json and yarn.lock
` 
It's removing package-lock.json and yarn.lock which make `npm ci --prod` not working

`npm ERR! The npm ci command can only install with an existing package-lock.json or
`

**Comment by maoo** [comment]
Thanks @josspo ! fixed by https://github.com/finos/security-scanning/pull/208
