### ISSUE TITLE
GitHub Action Configuration

### ISSUE THREAD

**Issue by robmoffat** [maoo/security-scanning#4]
Improve GitHub Actions to be installable on-click via a PR, without the need to update build descriptors, such as `pom.xml`, `build.gradle` or similar. See #5 , #6 and #7

It is also acceptable to write some documentation to instruct developers to copy/paste a certain block of code; this is an example coming from GitHub - https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle#using-the-gradle-starter-workflow

The GitHub Actions triggers should be:
- Run every day, at a certain time
- Everytime a PR is submitted, involving specific file names (see below)
- On each push, involcing specific file names (see below)

Specific file names are those defining build descriptors, such as `pom.xml`, `build.gradle`, `package.json`, `requirements.txt` or `pyproject.toml`, etc.

**Comment by maoo** [comment]
All done here! Gradle is a `wontfix`, as commented on https://github.com/maoo/security-scanning/issues/7 , and Scala is still WIP, see https://github.com/maoo/security-scanning/issues/6
